spring.application.name=faq

spring.datasource.url=jdbc:sqlite:faq.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Pode ser qualquer texto difícil e aleatorio!(NAO VAZE NUNCA)
api.security.token.secret=${JWT_SECRET:minha-senha-padrao-de-estudo}

# Pasta onde os áudios serão salvos locamente(PC Usuario)
app.upload.dir=uploads/audios
