spring.application.name=faq
# SupaBase
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --------------------------------------------

# --- CONFIGURACOES DA AZURE BLOB STORAGE ---
azure.storage.connection-string=${AZURE_CONNECTION_STRING}
azure.storage.container-name=${AZURE_CONTAINER}

# Pode ser qualquer texto difícil e aleatorio
api.security.token.secret=${JWT_SECRET}
